# Collaborative Filtering

This dataset contains user who rating the movies. We want to recommend the movie for user '220' using Collaborative Filtering by KNN and SVD Algorithm

In [3]:
# !pip install scikit-surprise

# for shell
# conda install -c conda-forge scikit-surprise

In [190]:
from surprise import Dataset
from surprise import Reader
import pandas as pd

In [212]:
# load dataset
df = pd.read_csv('dataset/movie/ratings.csv')
df_movie = pd.read_csv('dataset/movie/movies.csv')
reader = Reader(rating_scale=(1, 5))

In [237]:
df.drop('timestamp',axis=1)

        userId  movieId  rating
0            1        1     4.0
1            1        3     4.0
2            1        6     4.0
3            1       47     5.0
4            1       50     5.0
5            1       70     3.0
6            1      101     5.0
7            1      110     4.0
8            1      151     5.0
9            1      157     5.0
10           1      163     5.0
11           1      216     5.0
12           1      223     3.0
13           1      231     5.0
14           1      235     4.0
15           1      260     5.0
16           1      296     3.0
17           1      316     3.0
18           1      333     5.0
19           1      349     4.0
20           1      356     4.0
21           1      362     5.0
22           1      367     4.0
23           1      423     3.0
24           1      441     4.0
25           1      457     5.0
26           1      480     4.0
27           1      500     3.0
28           1      527     5.0
29           1      543     4.0
...        ...      ...     ...
100806     610   150401     3.0
100807     610   152077     4.0
100808     610   152081     4.0
100809     610   152372     3.5
100810     610   155064     3.5
100811     610   156371     5.0
100812     610   156726     4.5
100813     610   157296     4.0
100814     610   158238     5.0
100815     610   158721     3.5
100816     610   158872     3.5
100817     610   158956     3.0
100818     610   159093     3.0
100819     610   160080     3.0
100820     610   160341     2.5
100821     610   160527     4.5
100822     610   160571     3.0
100823     610   160836     3.0
100824     610   161582     4.0
100825     610   161634     4.0
100826     610   162350     3.5
100827     610   163937     3.5
100828     610   163981     3.5
100829     610   164179     5.0
100830     610   166528     4.0
100831     610   166534     4.0
100832     610   168248     5.0
100833     610   168250     5.0
100834     610   168252     5.0
100835     610   170875     3.0

[100836 rows x 3 columns]

In [238]:
#load from dataframe
data = Dataset.load_from_df(df[["userId", "movieId", "rating"]], reader)

## Algorithms Based on K-Nearest Neighbours (k-NN)

In [239]:
from surprise import KNNWithMeans

In [240]:
# # gridsearch
# from surprise.model_selection import GridSearchCV


# sim_options = {
#     "name": ["msd", "cosine"],
#     "min_support": [3, 4, 5],
#     "user_based": [False, True],
# }

# param_grid = {"sim_options": sim_options}

# gs = GridSearchCV(KNNWithMeans, param_grid, measures=["rmse", "mae"], cv=3)
# gs.fit(data)

# print(gs.best_score["rmse"])
# print(gs.best_params["rmse"])

In [241]:
algo = KNNWithMeans(sim_options={"name":"msd","user_base":True},k=20)

In [242]:
# algo.fit(data)
data_train = data.build_full_trainset()

In [243]:
algo.fit(data_train)

Computing the msd similarity matrix...
Done computing similarity matrix.

In [244]:
pred = pd.DataFrame()
# pred['movie'] = 
# pred

In [245]:
for i in range(1,len(df_movie)):
    pred.set_value(i,'movieId',i)
    pred.set_value(i,'predRating',algo.predict(220,i).est)

C:\Users\okky.qomarudin\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead

C:\Users\okky.qomarudin\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
  This is separate from the ipykernel package so we can avoid doing imports until

In [246]:
pred.sort_values('predRating',ascending=False)

      movieId  predRating
6427   6427.0    5.000000
876     876.0    5.000000
5490   5490.0    5.000000
5468   5468.0    5.000000
3096   3096.0    5.000000
5416   5416.0    5.000000
8477   8477.0    5.000000
467     467.0    5.000000
5328   5328.0    5.000000
3942   3942.0    5.000000
8405   8405.0    5.000000
5244   5244.0    5.000000
148     148.0    5.000000
7071   7071.0    5.000000
8335   8335.0    5.000000
3086   3086.0    5.000000
3951   3951.0    5.000000
495     495.0    5.000000
2801   2801.0    5.000000
3851   3851.0    5.000000
5817   5817.0    5.000000
6818   6818.0    5.000000
5772   5772.0    5.000000
3678   3678.0    5.000000
3792   3792.0    5.000000
5607   5607.0    5.000000
99       99.0    5.000000
3941   3941.0    5.000000
5537   5537.0    5.000000
496     496.0    5.000000
...       ...         ...
476     476.0    1.463768
2813   2813.0    1.455815
2417   2417.0    1.455815
4786   4786.0    1.455815
2892   2892.0    1.455815
6483   6483.0    1.452228
4412   4412.0    1.352111
8620   8620.0    1.324281
4580   4580.0    1.298663
8840   8840.0    1.275212
1519   1519.0    1.257886
178     178.0    1.222592
8677   8677.0    1.078197
5771   5771.0    1.064812
5672   5672.0    1.050114
5884   5884.0    1.000000
2742   2742.0    1.000000
2964   2964.0    1.000000
6967   6967.0    1.000000
8632   8632.0    1.000000
5560   5560.0    1.000000
3604   3604.0    1.000000
7312   7312.0    1.000000
7742   7742.0    1.000000
8494   8494.0    1.000000
6371   6371.0    1.000000
7114   7114.0    1.000000
8236   8236.0    1.000000
1574   1574.0    1.000000
5105   5105.0    1.000000

[9741 rows x 2 columns]

In [247]:
final_pred = pd.merge(left=pred,right=df_movie, left_on='movieId', right_on='movieId')
final_pred.sort_values('predRating',ascending=False).head(10)

,movieId,predRating,title,genres
536,633.0,5.0,Denise Calls Up (1995),Comedy
2711,3637.0,5.0,Vagabond (Sans toit ni loi) (1985),Drama
2835,3792.0,5.0,Duel in the Sun (1946),Drama|Romance|Western
5013,7767.0,5.0,"Best of Youth, The (La meglio gioventù) (2003)",Drama
2880,3851.0,5.0,I'm the One That I Want (2000),Comedy
4430,6545.0,5.0,I Capture the Castle (2003),Drama|Romance
4421,6533.0,5.0,"What's Up, Doc? (1972)",Comedy
5025,7815.0,5.0,True Stories (1986),Comedy|Musical
4414,6515.0,5.0,You Only Live Once (1937),Crime|Film-Noir
1647,2196.0,5.0,Knock Off (1998),Action

In [250]:
final_pred.predRating.describe()

count    5401.000000
mean        3.769918
std         0.683660
min         1.000000
25%         3.394928
50%         3.878399
75%         4.251019
max         5.000000
Name: predRating, dtype: float64

## Algorithm SVD

In [251]:
from surprise import SVD
# from surprise import Dataset
from surprise.model_selection import GridSearchCV

data = Dataset.load_from_df(df[["userId", "movieId", "rating"]], reader)

param_grid = {
    "n_epochs": [5, 10],
    "lr_all": [0.002, 0.005],
    "reg_all": [0.4, 0.6]
}
gs = GridSearchCV(SVD, param_grid, measures=["rmse", "mae"], cv=3)

gs.fit(data)

print(gs.best_score["rmse"])
print(gs.best_params["rmse"])

0.8935932971539516
{'n_epochs': 10, 'lr_all': 0.005, 'reg_all': 0.4}

In [ ]:
algoSVD = SVD(n_epochs=10,lr_all=0.005,reg_all=0.4,)

In [ ]:
algoSVD.fit(data_train)

In [ ]:
predSVD = pd.DataFrame()

In [ ]:
for i in range(1,len(df_movie)):
    predSVD.set_value(i,'movieId',i)
    predSVD.set_value(i,'predRating',algoSVD.predict(220,i).est)

In [ ]:
predSVD.sort_values('predRating',ascending=False)

In [ ]:
final_predSVD = pd.merge(left=predSVD,right=df_movie, left_on='movieId', right_on='movieId')
final_predSVD.sort_values('predRating',ascending=False).head(10)