# Collaborative Filtering

#### This dataset contains user who rating the movies. We want to recommend the movie for user '220' using Collaborative Filtering by KNN and SVD Algorithm

In [25]:
# !pip install scikit-surprise

# for shell
# conda install -c conda-forge scikit-surprise

In [26]:
from surprise import Dataset
from surprise import Reader
import pandas as pd

In [27]:
# load dataset
df = pd.read_csv('dataset/movie/ratings.csv')
df_movie = pd.read_csv('dataset/movie/movies.csv')
reader = Reader(rating_scale=(1, 5))

In [28]:
df.drop('timestamp',axis=1)

        userId  movieId  rating
0            1        1     4.0
1            1        3     4.0
2            1        6     4.0
3            1       47     5.0
4            1       50     5.0
5            1       70     3.0
6            1      101     5.0
7            1      110     4.0
8            1      151     5.0
9            1      157     5.0
10           1      163     5.0
11           1      216     5.0
12           1      223     3.0
13           1      231     5.0
14           1      235     4.0
15           1      260     5.0
16           1      296     3.0
17           1      316     3.0
18           1      333     5.0
19           1      349     4.0
20           1      356     4.0
21           1      362     5.0
22           1      367     4.0
23           1      423     3.0
24           1      441     4.0
25           1      457     5.0
26           1      480     4.0
27           1      500     3.0
28           1      527     5.0
29           1      543     4.0
...        ...      ...     ...
100812     610   156726     4.5
100813     610   157296     4.0
100814     610   158238     5.0
100815     610   158721     3.5
100816     610   158872     3.5
100817     610   158956     3.0
100818     610   159093     3.0
100819     610   160080     3.0
100820     610   160341     2.5
100821     610   160527     4.5
100822     610   160571     3.0
100823     610   160836     3.0
100824     610   161582     4.0
100825     610   161634     4.0
100826     610   162350     3.5
100827     610   163937     3.5
100828     610   163981     3.5
100829     610   164179     5.0
100830     610   166528     4.0
100831     610   166534     4.0
100832     610   168248     5.0
100833     610   168250     5.0
100834     610   168252     5.0
100835     610   170875     3.0
100836    9999        1     4.0
100837    9999    89745     4.0
100838    9999   102716     4.0
100839    9999   134853     4.0
100840    9999      586     4.0
100841    9999   131130     4.0

[100842 rows x 3 columns]

In [29]:
#load from dataframe
data = Dataset.load_from_df(df[["userId", "movieId", "rating"]], reader)

## Algorithm Based on K-Nearest Neighbours (k-NN)

In [30]:
from surprise import KNNWithMeans

In [31]:
# # gridsearch
# from surprise.model_selection import GridSearchCV


# sim_options = {
#     "name": ["msd", "cosine"],
#     "min_support": [3, 4, 5],
#     "user_based": [False, True],
# }

# param_grid = {"sim_options": sim_options}

# gs = GridSearchCV(KNNWithMeans, param_grid, measures=["rmse", "mae"], cv=3)
# gs.fit(data)

# print(gs.best_score["rmse"])
# print(gs.best_params["rmse"])

Define KNN

In [32]:


algo = KNNWithMeans(sim_options={"name":"msd","user_base":True},k=20)

Create data train

In [33]:
data_train = data.build_full_trainset()

Fit data train

In [34]:
algo.fit(data_train)

Computing the msd similarity matrix...
Done computing similarity matrix.

In [12]:
pred = pd.DataFrame()
# pred['movie'] = 
# pred

Recommend for user id 220

In [35]:
for i in range(1,len(df_movie)):
    pred.set_value(i,'movieId',i)
    pred.set_value(i,'predRating',algo.predict(9999,i).est)

C:\Users\okky.qomarudin\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead

C:\Users\okky.qomarudin\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
  This is separate from the ipykernel package so we can avoid doing imports until

In [36]:
pred.sort_values('predRating',ascending=False)

      movieId  predRating
3086   3086.0    5.000000
4426   4426.0    5.000000
4432   4432.0    5.000000
5867   5867.0    5.000000
4433   4433.0    5.000000
5833   5833.0    5.000000
4441   4441.0    5.000000
5817   5817.0    5.000000
4454   4454.0    5.000000
7091   7091.0    5.000000
8405   8405.0    5.000000
3357   3357.0    5.000000
7121   7121.0    5.000000
5772   5772.0    5.000000
4495   4495.0    5.000000
3379   3379.0    5.000000
8335   8335.0    5.000000
8477   8477.0    5.000000
4419   4419.0    5.000000
4021   4021.0    5.000000
2314   2314.0    5.000000
6159   6159.0    5.000000
85       85.0    5.000000
720     720.0    5.000000
6021   6021.0    5.000000
4342   4342.0    5.000000
3303   3303.0    5.000000
8580   8580.0    5.000000
3315   3315.0    5.000000
99       99.0    5.000000
...       ...         ...
3574   3574.0    1.544983
2862   2862.0    1.544983
1326   1326.0    1.523098
3597   3597.0    1.500822
2775   2775.0    1.500822
476     476.0    1.500000
2417   2417.0    1.492047
2813   2813.0    1.492047
2892   2892.0    1.492047
4786   4786.0    1.492047
6483   6483.0    1.446776
152     152.0    1.326765
4580   4580.0    1.324694
1999   1999.0    1.316456
8840   8840.0    1.311444
178     178.0    1.258824
8620   8620.0    1.119858
5771   5771.0    1.101044
3604   3604.0    1.027027
8632   8632.0    1.000000
7742   7742.0    1.000000
7564   7564.0    1.000000
6967   6967.0    1.000000
1574   1574.0    1.000000
8236   8236.0    1.000000
5884   5884.0    1.000000
2964   2964.0    1.000000
8494   8494.0    1.000000
5105   5105.0    1.000000
7114   7114.0    1.000000

[9741 rows x 2 columns]

#### Top 20 Recommended Movie for User Id 220 using KNN

In [38]:
final_pred = pd.merge(left=pred,right=df_movie, left_on='movieId', right_on='movieId')
final_pred.sort_values('predRating',ascending=False).head(500)

,movieId,predRating,title,genres
3186,4294.0,5.000000,"5,000 Fingers of Dr. T, The (1953)",Children|Fantasy|Musical
2639,3531.0,5.000000,All the Vermeers in New York (1990),Comedy|Drama|Romance
3759,5244.0,5.000000,Shogun Assassin (1980),Action|Adventure
2835,3792.0,5.000000,Duel in the Sun (1946),Drama|Romance|Western
841,1104.0,5.000000,"Streetcar Named Desire, A (1951)",Drama
3807,5328.0,5.000000,Rain (2001),Drama|Romance
3852,5416.0,5.000000,Cherish (2002),Comedy|Drama|Thriller
2740,3678.0,5.000000,"Man with the Golden Arm, The (1955)",Drama
87,99.0,5.000000,Heidi Fleiss: Hollywood Madam (1995),Documentary
3893,5468.0,5.000000,20 Million Miles to Earth (1957),Sci-Fi
3908,5490.0,5.000000,The Big Bus (1976),Action|Comedy
2735,3673.0,5.000000,Benji the Hunted (1987),Adventure|Children
2723,3655.0,5.000000,Blow-Out (La grande bouffe) (1973),Drama
2721,3653.0,5.000000,"Endless Summer, The (1966)",Documentary
2711,3637.0,5.000000,Vagabond (Sans toit ni loi) (1985),Drama
3936,5537.0,5.000000,Satin Rouge (2002),Drama|Musical
5154,8335.0,5.000000,Make Way for Tomorrow (1937),Drama
4054,5772.0,5.000000,My Dinner with André (1981),Drama
76,85.0,5.000000,Angels and Insects (1995),Drama|Romance
4077,5817.0,5.000000,Ararat (2002),Drama|War
4083,5833.0,5.000000,Dog Soldiers (2002),Action|Horror
936,1236.0,5.000000,Trust (1990),Comedy|Drama|Romance
5138,8238.0,5.000000,Little Murders (1971),Comedy|Crime
441,506.0,5.000000,Orlando (1992),Drama|Fantasy|Romance
4095,5867.0,5.000000,Thief (1981),Crime|Drama|Thriller
433,496.0,5.000000,What Happened Was... (1994),Comedy|Drama|Romance|Thriller
2599,3475.0,5.000000,"Place in the Sun, A (1951)",Drama|Romance
2597,3473.0,5.000000,Jonah Who Will Be 25 in the Year 2000 (Jonas q...,Comedy
5143,8261.0,5.000000,3 Women (Three Women) (1977),Drama
3274,4433.0,5.000000,Written on the Wind (1956),Drama
...,...,...,...,...
4516,6689.0,4.608043,"Battle of Shaker Heights, The (2003)",Comedy|Drama|Romance
3781,5285.0,4.608043,Lucky Break (2001),Comedy|Crime
2072,2751.0,4.608043,From the Hip (1987),Comedy|Drama
4588,6816.0,4.608043,Three O'Clock High (1987),Comedy
4911,7364.0,4.608043,Intermission (2003),Comedy|Crime|Drama
3858,5422.0,4.608043,"Emperor's New Clothes, The (2001)",Comedy
1246,1656.0,4.608043,Swept from the Sea (1997),Drama|Romance
3679,5068.0,4.608043,Beijing Bicycle (Shiqi sui de dan che) (2001),Drama
3681,5071.0,4.608043,Maelström (2000),Drama|Romance
2267,3008.0,4.608043,Last Night (1998),Drama|Sci-Fi
3307,4475.0,4.608043,"Beast of War, The (Beast, The) (1988)",Drama|War
3733,5178.0,4.608043,Fun (1994),Crime|Drama
2910,3900.0,4.608043,Crime and Punishment in Suburbia (2000),Comedy|Drama
2522,3378.0,4.608043,"Ogre, The (Unhold, Der) (1996)",Drama
4148,5968.0,4.608043,Miami Blues (1990),Comedy|Crime|Drama
4113,5896.0,4.608043,New Waterford Girl (1999),Comedy
4850,7251.0,4.608043,Where the Day Takes You (1992),Drama
4182,6027.0,4.608043,Dogfight (1991),Drama|Romance
4082,5829.0,4.608043,Men with Brooms (2002),Comedy|Drama|Romance
5369,8954.0,4.608043,Lightning in a Bottle (2004),Documentary
3371,4583.0,4.608043,Disorganized Crime (1989),Action|Comedy
851,1121.0,4.608043,Glory Daze (1995),Drama
2857,3823.0,4.608043,Wonderland (1999),Drama
2320,3074.0,4.607876,Jeremiah Johnson (1972),Western
700,918.0,4.607783,Meet Me in St. Louis (1944),Musical
2716,3643.0,4.607143,"Fighting Seabees, The (1944)",Action|Drama|War
2705,3628.0,4.607143,Flying Tigers (1942),Action|Drama|Romance|War
2577,3446.0,4.607143,Funny Bones (1995),Comedy|Drama
966,1267.0,4.606962,"Manchurian Candidate, The (1962)",Crime|Thriller|War
2209,2936.0,4.606127,Sullivan's Travels (1941),Adventure|Comedy|Romance

## Algorithm SVD

Grid Searh for finding best paramater

In [39]:
from surprise import SVD
# from surprise import Dataset
from surprise.model_selection import GridSearchCV

data = Dataset.load_from_df(df[["userId", "movieId", "rating"]], reader)

param_grid = {
    "n_epochs": [5, 10],
    "lr_all": [0.002, 0.005],
    "reg_all": [0.4, 0.6]
}
gs = GridSearchCV(SVD, param_grid, measures=["rmse", "mae"], cv=3)

gs.fit(data)

print(gs.best_score["rmse"])
print(gs.best_params["rmse"])

0.8941775120466015
{'n_epochs': 10, 'lr_all': 0.005, 'reg_all': 0.4}

Define SVD

In [40]:
algoSVD = SVD(n_epochs=10,lr_all=0.005,reg_all=0.4,)

Fit Data train

In [41]:
algoSVD.fit(data_train)

Make pandas for prediction

In [42]:
predSVD = pd.DataFrame()

Predict recommended Movie for User Id 220 with SVD

In [44]:
for i in range(1,len(df_movie)):
    predSVD.set_value(i,'movieId',i)
    predSVD.set_value(i,'predRating',algoSVD.predict(9999,i).est)

C:\Users\okky.qomarudin\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead

C:\Users\okky.qomarudin\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
  This is separate from the ipykernel package so we can avoid doing imports until

In [45]:
predSVD.sort_values('predRating',ascending=False)

      movieId  predRating
318     318.0    4.228561
858     858.0    4.172615
750     750.0    4.169867
904     904.0    4.164119
2959   2959.0    4.154741
1276   1276.0    4.139845
1104   1104.0    4.136206
1204   1204.0    4.129006
296     296.0    4.124697
1213   1213.0    4.113189
50       50.0    4.111192
260     260.0    4.108413
3508   3508.0    4.106270
1208   1208.0    4.106063
898     898.0    4.102488
1221   1221.0    4.100550
1089   1089.0    4.100153
4973   4973.0    4.098224
475     475.0    4.095378
1197   1197.0    4.093362
1196   1196.0    4.089375
2329   2329.0    4.088486
7361   7361.0    4.088414
1136   1136.0    4.088101
922     922.0    4.085541
1235   1235.0    4.084583
2571   2571.0    4.084228
912     912.0    4.082240
6350   6350.0    4.078331
5500   5500.0    4.077080
...       ...         ...
1381   1381.0    2.937602
3564   3564.0    2.926621
355     355.0    2.921860
3826   3826.0    2.918831
3248   3248.0    2.917287
762     762.0    2.915681
2053   2053.0    2.911938
2450   2450.0    2.906740
455     455.0    2.901090
312     312.0    2.898429
435     435.0    2.897023
5323   5323.0    2.886002
374     374.0    2.880603
2643   2643.0    2.876774
8666   8666.0    2.870751
3646   3646.0    2.862650
2412   2412.0    2.853529
1760   1760.0    2.847525
2798   2798.0    2.843313
193     193.0    2.833594
2720   2720.0    2.809178
1644   1644.0    2.808106
546     546.0    2.802043
2338   2338.0    2.792977
2701   2701.0    2.731418
1882   1882.0    2.730081
1562   1562.0    2.664060
1499   1499.0    2.662995
3593   3593.0    2.639494
1556   1556.0    2.561618

[9741 rows x 2 columns]

#### Top 20 Recommended Movie for User Id 220 using SVD

In [46]:
final_predSVD = pd.merge(left=predSVD,right=df_movie, left_on='movieId', right_on='movieId')
final_predSVD.sort_values('predRating',ascending=False).head(10)

,movieId,predRating,title,genres
277,318.0,4.228561,"Shawshank Redemption, The (1994)",Crime|Drama
659,858.0,4.172615,"Godfather, The (1972)",Crime|Drama
602,750.0,4.169867,Dr. Strangelove or: How I Learned to Stop Worr...,Comedy|War
686,904.0,4.164119,Rear Window (1954),Mystery|Thriller
2226,2959.0,4.154741,Fight Club (1999),Action|Crime|Drama|Thriller
975,1276.0,4.139845,Cool Hand Luke (1967),Drama
841,1104.0,4.136206,"Streetcar Named Desire, A (1951)",Drama
906,1204.0,4.129006,Lawrence of Arabia (1962),Adventure|Drama|War
257,296.0,4.124697,Pulp Fiction (1994),Comedy|Crime|Drama|Thriller
914,1213.0,4.113189,Goodfellas (1990),Crime|Drama